### PR TITLE
Fix password and email fields form builder methods

### LINKED ISSUE #21: methods that dont seem to inherit text_field
Example of what is shown when the method is not inherited 

screen shot 2016-03-25 at 21 51 36

```
  = user_fields.text_field :first_name
  = user_fields.text_field :last_name
  = user_fields.email_field :email
  = user_fields.email_field :email_confirmation
  = user_fields.password_field :current_password
```
### Fields currently identified as not inheriting.

- [x] email_field
- [x] password_field

### PR DESCRIPTION
**Pull request by aliuk2012**
Fixes #21
1. Added email and password attributes to the Person model.
2. Now applies GDS markup around email and password fields

### CODE REVIEW

File: spec/dummy/app/models/person.rb [hunk 1]
```diff
@@ -5,5 +5,9 @@ class Person
   validates_presence_of :name
 
   attr_accessor :ni_number
+  attr_accessor :email_work
+  attr_accessor :email_home
```
Comment (robmckinnon) [inline spec/dummy/app/models/person.rb]: Looks like we're not using the `email_home` field in the specs. Shall we delete it?

Comment (robmckinnon) [inline spec/dummy/app/models/person.rb]: My mistake, we are using it for the hint example.
